### ISSUE TITLE
Create Non-Existing Account Groups

### ISSUE THREAD

**Issue by lasuk** [macxred/cashctrl_ledger#18]
### Description

The `add_account` and `update_account` methods currently raise an error if the account's 'group' does not yet exist. The 'group' attribute is mapped to a CashCtrl 'category', representing a node in the category tree in Linux file-path style.

### Expected Behavior

The expected behavior is to automatically create the corresponding category on CashCtrl if the group does not already exist.

### Relevant Code

Code to generate categories for files is available at [cashctrl_api/client.py#L248-L261](https://github.com/macxred/cashctrl_api/blob/dde77e0c4ace495/cashctrl_api/client.py#L248-L261). It may be worth refactoring or isolating this code snippet to use it for both files and accounts.

### Possible Solution

- Refactor the category creation code to be reusable for both files and accounts.
- Modify the `add_account` and `update_account` methods to check if the group exists, and create it if it does not.

**Comment by AlexTheWizardL** [comment]
Tried to implement this.

Tried to replace this code:
```python
if group not in categories_map:
    raise ValueError(f"Group '{group}' does not exist.")
category_id = categories_map[group]
```
With this:
```python
if group not in categories_map:
    self._client.update_categories(resource='account', target=[group])
    categories = self._client.list_categories('account')
    categories_map = categories.set_index('path')['id'].to_dict()
category_id = categories_map[group]
```
But this causes an issue on CashCtrl side:

```python
>>> (Pdb) self.post(f"account/category/create.json", params={'name': 'hello'})
>>> *** requests.exceptions.HTTPError: API request failed with status 500: CashCtrl - 500 Internal Server Error
```

**Comment by lasuk** [comment]
What is the conentent of `group`?

Please provide a minimal reproducible example (a self contained python code snipped similar to [this](https://github.com/macxred/cashctrl_ledger/issues/25#issuecomment-2138098295).

**Comment by AlexTheWizardL** [comment]
To reproduce this issue:

1. Change the existing code here [cashctrl_ledger/ledger.py#L179-184](https://github.com/macxred/cashctrl_ledger/blob/bb148f9b268728a009f22d67bda1d61f52dbade2/cashctrl_ledger/ledger.py#L179C1-L184C39) to the following:
```python
if group not in categories_map:
    self._client.update_categories(resource='account', target=[group])
    categories = self._client.list_categories('account')
    categories_map = categories.set_index('path')['id'].to_dict()
category_id = categories_map[group]
```
2. Run this snippet of code after:
```python
from cashctrl_ledger import CashCtrlLedger

cashctrl_ledger = CashCtrlLedger()
cashctrl_ledger.add_account(account=1144, currency='USD',
    text='test account', vat_code='TestCodeAccounts', group='/abc'
)
```
3. Receive such an error:
```python
>>> ## requests.exceptions.HTTPError: API request failed with status 500: CashCtrl - 500 Internal Server Error
```

**Comment by lasuk** [comment]
Minimal reproducible example

```python
from cashctrl_api import CashCtrlClient
client = CashCtrlClient()

# Updating an existing account category works
categories = client.list_categories('account')
existing_category = categories.at[0, 'path']
client.update_categories(resource='account', target=[existing_category])

# Updating a non-existing account category fails
client.update_categories(resource='account', target=['/abc'])
```
Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lukas/macx/cashctrl_api/cashctrl_api/client.py", line 259, in update_categories
    response = self.post(f"{resource}/category/create.json",
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukas/macx/cashctrl_api/cashctrl_api/client.py", line 105, in post
    return self.json_request("POST", endpoint, data=data, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukas/macx/cashctrl_api/cashctrl_api/client.py", line 85, in json_request
    response = self.request(method, endpoint, data=data, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukas/macx/cashctrl_api/cashctrl_api/client.py", line 64, in request
    raise HTTPError("API request failed with status "
requests.exceptions.HTTPError: API request failed with status 500: CashCtrl - 500 Internal Server Error
```

**Comment by AlexTheWizardL** [comment]
> Are you sure the line numbers in the link provided above are correct? [cashctrl_ledger/ledger.py#L179-184](https://github.com/macxred/cashctrl_ledger/blob/bb148f9b268728a009f22d67bda1d61f52dbade2/cashctrl_ledger/ledger.py#L179C1-L184C39) (The code block is about vat_codes, not categories)

Sorry, lines should be #L188-190, I`ve updated the comment

**Comment by lasuk** [comment]
Narrowing in on the error.

This snippet:
```python
from cashctrl_api import CashCtrlClient
client = CashCtrlClient()
params = {"name": "hi_there", "parentId": 53} # id 53 matches '/Anlagevermögen'
client.post("account/category/create.json", params=params)
```
Generates the same error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lukas/macx/cashctrl_api/cashctrl_api/client.py", line 105, in post
    return self.json_request("POST", endpoint, data=data, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukas/macx/cashctrl_api/cashctrl_api/client.py", line 85, in json_request
    response = self.request(method, endpoint, data=data, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukas/macx/cashctrl_api/cashctrl_api/client.py", line 64, in request
    raise HTTPError("API request failed with status "
requests.exceptions.HTTPError: API request failed with status 500: CashCtrl - 500 Internal Server Error
```

**Comment by lasuk** [comment]
The error does not appear when providing a number to the `category/create` API call:
```python
from cashctrl_api import CashCtrlClient
client = CashCtrlClient()
params = {"name": "hi_there", "parentId": 53, "number": "1020"} # id 53 matches '/Anlagevermögen'
response = client.post("account/category/create.json", params=params)
```
The code seems to work fine:
```python
print(response)
## {'success': True, 'message': 'Category saved', 'insertId': 94}

client.list_categories('account')
##                                                  path  id                   created createdBy  ...                                       text     cls   leaf isSystem
## 14                                    /Anlagevermögen  53 2024-04-26 09:17:48+02:00    SYSTEM  ...                             Anlagevermögen  folder  False    False
## [..snip..]
## 7                            /Anlagevermögen/hi_there  94 2024-06-03 18:13:19+02:00  API:DMHr  ...                                   hi_there  folder   True    False
## [..snip..]
```

Learnings:
- Providing a number to the `category/create` API endpoint is _not optional_ (contradicting the [manual](https://app.cashctrl.com/static/help/en/api/index.html#/account/category/create.json) that states the number _is optional_).
- CashCtrl does not handle the missing number with a graceful error message.

**Comment by AlexTheWizardL** [comment]
@lasuk Yeah, works for me. Thanks for debugging!

**Comment by AlexTheWizardL** [comment]
Creating an account category without specifying parentId will produce an error.

Code snippet:
```python
from cashctrl_api import CashCtrlClient
client = CashCtrlClient()

# Will create the category for files without parentId
params = {
  'name': '/name',
}
client.post("file/category/create.json", params=params)

# Will not create the category for account without parentId
params = {
  'name': '/name',
  'number': 1020,
}
client.post("account/category/create.json", params=params)
```

Generated error:
```
Traceback (most recent call last):
  File "/Users/oleksandrstepanenko/macx/cashctrl_api/kkk.py", line 15, in <module>
    client.post("account/category/create.json", params=params)
  File "/Users/oleksandrstepanenko/macx/cashctrl_api/cashctrl_api/client.py", line 105, in post
    return self.json_request("POST", endpoint, data=data, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oleksandrstepanenko/macx/cashctrl_api/cashctrl_api/client.py", line 96, in json_request
    raise RequestException(f"API call failed. {msg}")
requests.exceptions.RequestException: API call failed. parentId: This field cannot be empty.
```
